---
ID: "767dac39-644b-4f78-b3f4-1e4c61dc403b"
Parent: "1ffe6566-2d56-4113-894b-4212640f19e9"
Template: "1ffe6566-2d56-4113-894b-4212640f19e9"
Path: /sitecore/templates/blog/Article/__Standard Values
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{892F2DC4-2E6F-473B-9D09-258621398FE2}">
        <r
          id="{DFA4A05F-01E1-407B-857D-6B0C33ABB95E}"
          ph="/main"
          uid="{86921FF0-27C6-4B59-ADE0-351C8AB7A863}" />
      </d>
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180303T032616Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
