---
ID: "0f34501b-c9c9-4501-8602-9cbc37dd7e30"
Parent: "bcd5368b-b03b-4e1a-a438-50e31aaeea61"
Template: "bcd5368b-b03b-4e1a-a438-50e31aaeea61"
Path: /sitecore/templates/blog/ArticlePreview/__Standard Values
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180303T172251Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
